dist: trusty

language: python

python: 3.7

cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
    - master
    - /^\d.\d+$/

install: pip install -r requirements.txt

script: make SPHINXOPTS=-nW html

notifications:
  email: false

git:
  depth: 1
